version: "3"

env:
  MAIN: src/main.py
  EXTRACT_FEATURES: src/model_features/extract_all.py
  MPI_EXTRACT_FEATURES: src/model_features/mpi_extract_all.py
  COMPILER: /usr/bin/clang++
  DEBUG_FLAGS: -g -Wall -fsanitize=address

tasks:
  default:
    cmds:
      - task: select-data
      - task: train-thermal
      - task: train-solvent
      - task: train-water
      - task: run-client

  # Feature extraction
  extract-all:
    cmds:
      - python ${EXTRACT_FEATURES} {{.CLI_ARGS}}
      - task: check-features

  mpi-extract-all:
    cmds:
      - python ${MPI_EXTRACT_FEATURES} {{.CLI_ARGS}}
      - task: check-features

  extract-feature:
    cmds:
      - python src/model_features/feature_extraction.py {{.CLI_ARGS}}

  check-features:
    cmds:
      - python data/check_features.py

  select-data:
    cmds:
      - python src/model_features/data_selection.py

  # Model training and testing
  train-thermal:
    cmds:
      - python src/model_training/thermal_model.py

  test-thermal:
    cmds:
      - python src/model_training/thermal_model_test.py

  train-solvent:
    cmds:
      - python src/model_training/solvent_model.py

  test-solvent:
    cmds:
      - python src/model_training/solvent_model_test.py

  train-water:
    cmds:
      - python src/model_training/water_stability_model.py

  test-water:
    cmds:
      - python src/model_training/water_stability_model_test.py

  # MOF database for nearest neighbor query
  run-client:
    cmds:
      - python -m src.app

  # zeo++ library
  compile-zeo:
    cmds:
      - task: clean-zeo
      - (cd zeo++-0.3/voro++/src && make)
      - (cd zeo++-0.3 && make)

  clean-zeo:
    cmds:
      - (cd zeo++-0.3/voro++/src && make clean)
      - (cd zeo++-0.3 && make clean)

  # Clean
  clean-all:
    cmds:
      - rm -r temp_* || true
      - rm data/all_in_one.pkl || true
      - rm data/all_in_one_cols.pkl || true
      - rm data/*/*_split_data.pkl || true
      - rm model/*.pkl || true
      - rm model/preprocess/*.pkl || true

  clean-temp:
    cmds:
      - rm -r temp_* || true
