"""feature_extraction.py
Extract training features from .cif files using Zeo++ library
and RAC_finder module. 

Reconstructed feature extraction pipeline. 

Important Notes: 
- Only supports openbabel 2.4.1 for RAC extraction. 
- openbabel 2.4.1 only supports python version < 3.8

Reference: 
- https://github.com/hjkgrp/MOFSimplify
"""

import sys
import os
import subprocess
import shutil
import numpy as np
import pandas as pd

def extract_features(project_path, target_path, id=""):
    """
    Extract features from one cif file specified by target_path. This function is 
    thread-safe provided that id is different. 

    :param project_path: str, root path of the predictor project
    :param target_path: str, the name of the MOF being analyzed 
    :param prediction_type: str, the type of prediction being run. Can be 'solvent' or 'thermal'
    :param id: str, id for the current feature extraction session

    :return: the DataFrame merged_df containing features generated by both Zeo++ and RAC. This 
    DataFrame will be empty if feature extraction failed and error will be thrown. 
    """
    # Error handler 
    def error_handler(): 
        print(f"[{id}] ERROR: I/O pipeline broken when processing {target_path}")
        return pd.DataFrame([]) # Return empty data frame if failed

    # Reinitialize: remove existing temp directory
    temp_dir = os.path.join(project_path, f"temp_{id}")

    # Print warning if there's feature extraction in progress 
    if (f"temp_{id}") in os.listdir(project_path):
        temp_found_warning = "WARNING: There is another feature extraction in progress for the same file. Overwrite? [y/n] "
        while True: 
            temp_found_cmd = input(temp_found_warning)
            if (temp_found_cmd == "y"): 
                print("Feature extraction proceeds...")
                break
            elif (temp_found_cmd == "n"): 
                print("Feature extraction terminated by user...")
                return error_handler()
            else: 
                print(f"Invalid option {temp_found_cmd}")

        shutil.rmtree(temp_dir)
    
    os.mkdir(temp_dir)
    
    cif_dir = os.path.join(temp_dir, "cifs") 
    cif_copy_path = os.path.join(cif_dir, "temp.cif")
    if "cifs" in os.listdir(project_path):
        shutil.rmtree(cif_dir)
    os.mkdir(cif_dir)
    shutil.copyfile(target_path, cif_copy_path)

    # Construct temp folder structure
    feature_dir = os.path.join(temp_dir, "features")
    RAC_dir = os.path.join(feature_dir, "RAC")
    zeo_dir = os.path.join(feature_dir, "zeo++")
    os.mkdir(feature_dir)
    os.mkdir(RAC_dir)
    os.mkdir(zeo_dir)
    
    # Generate features 
    cif_primitive_path = os.path.join(cif_dir, "temp_primitive.cif")
    shutil.copy(cif_copy_path, cif_primitive_path)

    # Define path variables for clarity 
    zeo_path = os.path.join(project_path, "zeo++-0.3/network")
    RAC_finder_path = os.path.join(project_path, "src", "model_features", "RAC_finder.py")

    pd_path = os.path.join(zeo_dir, "temp_pd.txt")
    sa_path = os.path.join(zeo_dir, "temp_sa.txt")
    pov_path = os.path.join(zeo_dir, "temp_pov.txt")

    # cmd1, cmd2, and cmd3 are for Zeo++. cmd4 is for RACs.
    cmd1 = (
        zeo_path
        + " -ha -res "
        + pd_path
        + " "
        + cif_primitive_path
    )
    cmd2 = (
        zeo_path
        + " -sa 1.86 1.86 10000 "
        + sa_path
        + " "
        + cif_primitive_path
    )
    cmd3 = (
        zeo_path
        + " -volpo 1.86 1.86 10000 "
        + pov_path
        + " "
        + cif_primitive_path
    )
    cmd4 = (
        "python "
        + RAC_finder_path
        + " %s %s" % (cif_primitive_path, RAC_dir)
    )

    # WARNING: This must run sequentially, as the whole function is running in 
    # parallel. Running extra subprocesses causes overhead. 
    process = subprocess.Popen(
        cmd1, stdout=subprocess.PIPE, stderr=None, shell=True
    )
    output1 = process.communicate()[0]

    process = subprocess.Popen(
        cmd2, stdout=subprocess.PIPE, stderr=None, shell=True
    )
    output = process.communicate()[0]

    process = subprocess.Popen(
        cmd3, stdout=subprocess.PIPE, stderr=None, shell=True
    )
    output3 = process.communicate()[0]

    process = subprocess.Popen(
        cmd4, stdout=subprocess.PIPE, stderr=None, shell=True
    )
    output4 = process.communicate()[0]



    # Extract features from output files

    """ 
    The geometric descriptors are:
    - the maximum included sphere (Di)
    - maximum free sphere (Df)
    - maximum included sphere in the free sphere path (Dif)
    - gravimetric pore volume (GPOV)
    - volumetric pore volume (VPOV)
    - gravimetric surface area (GSA)
    - volumetric surface area (VSA)
    - cell volume (cell_v)
    - gravimetric pore accessible volume (GPOAV)
    - gravimetric pore non-accessible volume (GPONAV)
    - pore-accessible volume (POAV)
    - pore non-accessible volume (PONAV)
    - pore accessible void fraction (POAVF)
    - pore nonaccessible void fraction (PONAVF)

    All Zeo++ calculations use a probe radius of 1.86 angstrom, and zeo++ is called by subprocess.
    """

    dict_list = []
    cif_file = cif_copy_path + "_primitive.cif"
    basename = cif_file.strip(".cif")
    (
        largest_included_sphere,
        largest_free_sphere,
        largest_included_sphere_along_free_sphere_path,
    ) = (np.nan, np.nan, np.nan)
    unit_cell_volume, crystal_density, VSA, GSA = np.nan, np.nan, np.nan, np.nan
    VPOV, GPOV = np.nan, np.nan
    POAV, PONAV, GPOAV, GPONAV, POAV_volume_fraction, PONAV_volume_fraction = (
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        np.nan,
    )

    if (
        os.path.exists(os.path.join(zeo_dir, "temp_pd.txt"))
        & os.path.exists(os.path.join(zeo_dir, "temp_sa.txt"))
        & os.path.exists(os.path.join(zeo_dir, "temp_pov.txt"))
    ):
        with open(pd_path) as f:
            pore_diameter_data = f.readlines()
            for row in pore_diameter_data:
                largest_included_sphere = float(
                    row.split()[1]
                )  # largest included sphere
                largest_free_sphere = float(row.split()[2])  # largest free sphere
                largest_included_sphere_along_free_sphere_path = float(
                    row.split()[3]
                )  # largest included sphere along free sphere path
        with open(sa_path) as f:
            surface_area_data = f.readlines()
            for i, row in enumerate(surface_area_data):
                if i == 0:
                    unit_cell_volume = float(
                        row.split("Unitcell_volume:")[1].split()[0]
                    )  # unit cell volume
                    crystal_density = float(
                        row.split("Density:")[1].split()[0]
                    )  # crystal density
                    VSA = float(
                        row.split("ASA_m^2/cm^3:")[1].split()[0]
                    )  # volumetric surface area
                    GSA = float(
                        row.split("ASA_m^2/g:")[1].split()[0]
                    )  # gravimetric surface area
        with open(pov_path) as f:
            pore_volume_data = f.readlines()
            for i, row in enumerate(pore_volume_data):
                if i == 0:
                    density = float(row.split("Density:")[1].split()[0])
                    POAV = float(
                        row.split("POAV_A^3:")[1].split()[0]
                    )  # Probe accessible pore volume
                    PONAV = float(
                        row.split("PONAV_A^3:")[1].split()[0]
                    )  # Probe non-accessible probe volume
                    GPOAV = float(row.split("POAV_cm^3/g:")[1].split()[0])
                    GPONAV = float(row.split("PONAV_cm^3/g:")[1].split()[0])
                    POAV_volume_fraction = float(
                        row.split("POAV_Volume_fraction:")[1].split()[0]
                    )  # probe accessible volume fraction
                    PONAV_volume_fraction = float(
                        row.split("PONAV_Volume_fraction:")[1].split()[0]
                    )  # probe non accessible volume fraction
                    VPOV = POAV_volume_fraction + PONAV_volume_fraction
                    GPOV = VPOV / density
    else:
        print(
            "Not all 3 files exist, so at least one Zeo++ call failed!",
            "sa: ",
            os.path.exists(sa_path),
            "; pd: ",
            os.path.exists(pd_path),
            "; pov: ",
            os.path.exists(pov_path),
        )
        return error_handler()
    
    geo_dict = {
        "name": basename,
        "cif_file": cif_file,
        "Di": largest_included_sphere,
        "Df": largest_free_sphere,
        "Dif": largest_included_sphere_along_free_sphere_path,
        "cell_v": unit_cell_volume,
        "VSA": VSA,
        "GSA": GSA,
        "VPOV": VPOV,
        "GPOV": GPOV,
        "POAV_vol_frac": POAV_volume_fraction,
        "PONAV_vol_frac": PONAV_volume_fraction,
        "GPOAV": GPOAV,
        "GPONAV": GPONAV,
        "POAV": POAV,
        "PONAV": PONAV,
    }
    dict_list.append(geo_dict)
    geo_df = pd.DataFrame(dict_list)

    # error handling for cmd4
    with open(os.path.join(RAC_dir, "RAC_getter_log.txt"), "r") as f:
        if f.readline() == "FAILED":
            print("RAC generation failed.")
            return error_handler()
            
    try:
        lc_df = pd.read_csv(os.path.join(RAC_dir, "lc_descriptors.csv"))
        sbu_df = pd.read_csv(os.path.join(RAC_dir, "sbu_descriptors.csv"))
        linker_df = pd.read_csv(os.path.join(RAC_dir, "linker_descriptors.csv"))
    except Exception:  # csv files have been deleted
        return error_handler()

    # Take mean
    lc_df_numeric_mean = lc_df.select_dtypes(include=[np.number]).mean().to_frame().transpose()
    sbu_df_numeric_mean = sbu_df.select_dtypes(include=[np.number]).mean().to_frame().transpose()
    linker_df_numeric_mean = linker_df.select_dtypes(include=[np.number]).mean().to_frame().transpose()

    merged_df = pd.concat([geo_df, lc_df_numeric_mean, sbu_df_numeric_mean, linker_df_numeric_mean], axis=1)
    shutil.rmtree(temp_dir) # Remove temp directory
    return merged_df


# Generate descriptors based on a test file
if __name__ == "__main__":

    print("***Running feature_extraction as main***")
    project_path = os.path.abspath(".")

    target: str = ""
    if len(sys.argv) == 1: 
        target = "ABAVIJ_clean"
        target_path = os.path.join(project_path, "test", "ABAVIJ_clean.cif")
        print(f"No target given. Running feature extraction on {target}")
    else: 
        target = sys.argv[1]
        target_path = os.path.join(project_path, target)

    # Generate descriptors 
    result = extract_features(project_path, target_path, "thermal", id=target)
    if result.empty: 
        print("generate_descriptors exit due to failure")
        exit(1)
    
    # Print out features obtained 
    print("Print features obtained: ")
    print(result)
    print("***feature_extraction exited successfully***")
